/////////////////////////////////////////////////////////////////////////////
// Author:      PB
// Copyright:   (c) 2012 PB <pbfordev@gmail.com>
// Licence:     wxWindows licence
/////////////////////////////////////////////////////////////////////////////


#ifndef _WXAUTOEXCEL_VERSION_H
#define _WXAUTOEXCEL_VERSION_H

#define WXAUTOEXCEL_MAJOR_VERSION     2
#define WXAUTOEXCEL_MINOR_VERSION     0
#define WXAUTOEXCEL_RELEASE_NUMBER    0
#define WXAUTOEXCEL_SUBRELEASE_NUMBER 0


#define WXAUTOEXCEL_STRINGIZE_(x) #x
#define WXAUTOEXCEL_STRINGIZE(x) WXAUTOEXCEL_STRINGIZE_(x)

#define WXAUTOEXCEL_VERSION_NUM_STRING \
    WXAUTOEXCEL_STRINGIZE(WXAUTOEXCEL_MAJOR_VERSION) WXAUTOEXCEL_STRINGIZE(WXAUTOEXCEL_MINOR_VERSION) WXAUTOEXCEL_STRINGIZE(WXAUTOEXCEL_RELEASE_NUMBER)
#define WXAUTOEXCEL_VERSION_NUM_DOT_STRING \
    WXAUTOEXCEL_STRINGIZE(WXAUTOEXCEL_MAJOR_VERSION) "." WXAUTOEXCEL_STRINGIZE(WXAUTOEXCEL_MINOR_VERSION) "." WXAUTOEXCEL_STRINGIZE(WXAUTOEXCEL_RELEASE_NUMBER)

#endif //#ifndef _WXAUTOEXCEL_VERSION_H
