/////////////////////////////////////////////////////////////////////////////
// Author:      PB
// Copyright:   (c) 2012 PB <pbfordev@gmail.com>
// Licence:     wxWindows licence
/////////////////////////////////////////////////////////////////////////////

/**********************************************************

wxAutoExcel Print sample demonstrates:
- How to fill a Range.
- How to set-up page properties of a worksheet, including customising its header and footer.

**********************************************************/



#include <wx/wx.h>
#include <wx/stdpaths.h>
#include <wx/filename.h>

#include <wx/wxAutoExcel.h>

class MyFrame : public wxFrame
{
public:
    MyFrame();    
private:    
    void OnCreateWorksheet(wxCommandEvent& event);
    void OnQuit(wxCommandEvent& event);    
};


class MyApp : public wxApp
{
public:	
    virtual bool OnInit();    
};

using namespace wxAutoExcel;


MyFrame::MyFrame()
: wxFrame(NULL, wxID_ANY, _("wxAutoExcel Print sample"))
{
    wxMenu *menu = new wxMenu;
    menu->Append(wxID_NEW, _("&Show me!"));
    menu->Append(wxID_EXIT, _("E&xit"));

    wxMenuBar *menuBar = new wxMenuBar();
    menuBar->Append(menu, _("&Sample"));
    SetMenuBar(menuBar);

    Bind(wxEVT_COMMAND_MENU_SELECTED, &MyFrame::OnCreateWorksheet, this, wxID_NEW);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &MyFrame::OnQuit, this, wxID_EXIT);
}

void MyFrame::OnCreateWorksheet(wxCommandEvent& WXUNUSED(event))
{
    // first create an instance of MS Excel
    wxExcelApplication app = wxExcelApplication::CreateInstance();
    if ( !app ) 
    {
        wxLogError(_("Failed to create an instance of MS Excel application."));
        return;
    }    
    app.SetVisible(true); // display MS Excel window

    // add a new workbook
    wxExcelWorkbook workbook = app.GetWorkbooks().Add();    
    if ( !workbook ) 
    {
        wxLogError(_("Failed to create a new workbook."));
        return;
    }

    // get the first worksheet in the newly added workbook
    wxExcelWorksheet worksheet = workbook.GetWorksheets()[1];
    if ( !worksheet )
    {
        wxLogError(_("Failed to obtain worksheet number 1."));
        return;
    }

    // Fill the worksheet with some values first    
    wxVariant variant;
    wxExcelRange range;
    long columns;    

    range = worksheet.GetRange("A1:BZ1");
    columns = range.GetColumns().GetCount();

    app.SetStatusBar("Filling data...");
    app.SetScreenUpdating(false);

    variant.ClearList();
    for (long l = 0; l < columns; l++)
        variant.Append(wxString::Format("Col %ld", l+1));
    range = variant;
    range.GetFont().SetBold(true);

    range = worksheet.GetRange("A2:BZ2");    
    for ( int i = 0; i < 2; i++ )
    {
        variant.ClearList();        
        variant.Append(wxString::Format("Row %ld", i+2));
        for (long l = 0; l < columns - 1; l++)
            variant.Append(i+l+2);
        range = variant;
        range = range.GetOffset(1);
    }
    worksheet.GetRange("A2:A3").GetFont().SetBold(true);

    range = worksheet.GetRange("A2:BZ3");    
    wxExcelRange fillRange = worksheet.GetRange("A2:BZ100");
    range.AutoFill(fillRange, WXAEEP(xlFillSeries)); 

    worksheet.GetUsedRange().GetEntireColumn().AutoFit();        

    worksheet.SetAutomationLCID_(wxExcelObject::lcidEnglishUS);
    wxExcelPageSetup pageSetup = worksheet.GetPageSetup();    

    pageSetup.SetPrintGridlines(true);
    pageSetup.SetPrintTitleColumns("$A:$A");
    pageSetup.SetPrintTitleRows("$1:$1");
    pageSetup.SetOrientation(xlLandscape);

    // see here for formatting codes http://msdn.microsoft.com/en-us/library/office/bb225426%28v=office.12%29.aspx
    pageSetup.SetCenterHeader("&B&A&B");
    pageSetup.SetRightHeader("&G &I&08 Generated by wxAutoExcel");
    
    // Check if the bitmap to be added add to the header actually exists
    wxStandardPaths::Get().DontIgnoreAppSubDir();
    wxString picturePath = wxStandardPaths::Get().GetResourcesDir() + "\\wxAutoExcel small.bmp";
    
    if ( !wxFileName::FileExists(picturePath) )
    {
        picturePath = wxStandardPaths::Get().GetResourcesDir() + "\\..\\wxAutoExcel small.bmp";
        if ( !wxFileName::FileExists(picturePath) )
        {
           wxLogMessage(_("Could not find the sample file (%s)."), picturePath);        
           picturePath.clear();
        }                  
    }
    if ( !picturePath.empty() )
    {
        wxExcelGraphic graphic = pageSetup.GetRightHeaderPicture();
        graphic.SetFilename(picturePath);
        graphic.SetLockAspectRatio(msoTrue);
        graphic.SetHeight(graphic.GetHeight() / 2);    
    }   

    pageSetup.SetRightFooter("Page &P of &N");

    app.SetStatusBar();
    app.SetScreenUpdating(true);

    worksheet.PrintPreview();

}

void MyFrame::OnQuit(wxCommandEvent& WXUNUSED(event))
{
    Close(true);
}


bool MyApp::OnInit()
{
    if (!wxApp::OnInit())
        return false;       	
    MyFrame* frame = new MyFrame();
    frame->Show();

    wxLog::AddTraceMask(wxTRACE_AutoExcel);                                  

    return true;
}

IMPLEMENT_APP(MyApp)
