name: Build with MSVS 2022 and wxWidgets GIT master

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/build-msys2.yml'
      - '.github/workflows/build-online-docs.yml'
      - 'docs/**'
      - 'util/**'
      - 'ReadMe.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/build-msys2.yml'
      - '.github/workflows/build-online-docs.yml'
      - 'docs/**'
      - 'util/**'
      - 'ReadMe.md'
  workflow_dispatch:

permissions:
  contents: read

env:
  WX_SRC_DIR: /wx-src
  WX_BUILD_DIR: /wx-build
  WX_INST_DIR: /wx-installed
  WX_PRIV_DIR: /include/wx/msw/private/
  WX_HASH_MASK: /wx-installed/**/*
  AE_BUILD_DIR: /ae-build-cmake

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache wxWidgets
        id: cache-wxwidgets
        uses: actions/cache@v3
        with:
          path: ${{ env.WX_INST_DIR }}
          key: wxWidgets-${{ runner.os }}-${{ hashFiles(env.WX_HASH_MASK) }}
          restore-keys: |
            wxWidgets-${{ runner.os }}-

      - name: Clone, build, and install wxWidgets (if not cached)
        if: steps.cache-wxwidgets.outputs.cache-hit != 'true'
        run: |
          git clone --recurse-submodules https://github.com/wxWidgets/wxWidgets.git ${{ env.WX_SRC_DIR }}
          mkdir ${{ env.WX_BUILD_DIR }}
          cd ${{ env.WX_BUILD_DIR }}
          cmake -G "Visual Studio 17 2022" -DCMAKE_CXX_STANDARD=20 -DBUILD_SHARED_LIBS=ON -DwxBUILD_SAMPLES=OFF -DwxUSE_AUI=OFF -DwxUSE_DEBUGREPORT=OFF -DwxUSE_EXPAT=OFF -DwxUSE_GLCANVAS=OFF -DwxUSE_GRID=OFF -DwxUSE_MEDIACTRL=OFF -DwxUSE_PROPGRID=OFF -DwxUSE_RIBBON=OFF -DwxUSE_RICHTEXT=OFF -DwxUSE_STC=OFF -DwxUSE_WEBVIEW=OFF -DwxUSE_DATAVIEWCTRL=OFF -DwxUSE_TREELISTCTRL=OFF -DwxUSE_REGEX=OFF -DwxUSE_XML=OFF -DwxUSE_WEBREQUEST=OFF -DwxUSE_XRC=OFF -DwxUSE_LIBJPEG=OFF -DwxUSE_LIBTIFF=OFF -DwxUSE_TGA=OFF -S ${{ env.WX_SRC_DIR }} -B .

          cmake --build . --config Debug
          cmake --install . --config Debug --prefix ${{ env.WX_INST_DIR }}
          # wxWidgets does not install private headers we need to copy them by our own
          # neither copy nor xcopy seem to support paths with forward slashes, 
          # so robocopy is used. robocopy returns non-zero exit codes even when there were
          # no errors, so the workaround after semicolon is needed.
          robocopy ${{ env.WX_SRC_DIR }}${{ env.WX_PRIV_DIR }} ${{ env.WX_INST_DIR }}${{ env.WX_PRIV_DIR }}; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
          
      - name: Configure wxAutoExcel
        run: |
          mkdir ${{ env.AE_BUILD_DIR }}
          cd ${{ env.AE_BUILD_DIR }}
          cmake -G "Visual Studio 17 2022" -DCMAKE_CXX_STANDARD=20 -DBUILD_SHARED_LIBS=ON -DwxWidgets_ROOT_DIR=${{ env.WX_INST_DIR }} -S ${{ github.workspace }} -B .

      - name: Build wxAutoExcel
        run: |
          cd ${{ env.AE_BUILD_DIR }}
          cmake --build . --config Debug