name: Update Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'include/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get -q -o=Dpkg::Use-Pty=0 -y install doxygen graphviz
          
      - name: Generate documentation
        working-directory: docs/doxygen
        run: |
          doxygen Doxyfile

     - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/doxygen/out/html

